languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 2
rtl = false

title = "Ben Petterborg"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params]
   mainSections = ["Posts", "Projects"]

[author]
  name = "Ben Petterborg"
  image = "img/author.jpg"
  headline = "Software Engineering Major"
  bio = "A little bit about you"
  links = [
      { email = "mailto:hello@ben-p.dev" },
      { github = "https://github.com/bpetterborg" }
  ]
